url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Learning Resource Center"

site_policies_link: https://www.umass.edu/gateway/site-policies
webmaster_email: sbandrews@umass.edu

navbar_links:
  - name: Opportunities
    link: opportunities.html
  - name: Students
    link: students.html
  - name: LRC
    link: https://www.umass.edu/lrc/

navbar_dropdown_title: Staff
navbar_dropdown_links:
  - name: Staff Page
    link: staff.html
  - name: Staff Login
    link: https://oursoffice.umass.edu/

# For every alert you would like to add, specify:
#  - text: the text for the alert, e.g. "The LRC will be closed tomorrow."
#  - type: what type the alert is/what color it should display as. Options are:
#     * info -- light blue
#     * warning -- yellow
#     * danger -- red
#  - id: should be a string of letters, numbers, and dashes ('-') that has
#        never been used as an alert ID before. I recommend generating a random
#        string from random.org.
#  - dismissable: whether users can dismiss the alert by clicking an X button
alerts:
  - text: The LRC is hiring peer tutors, SI leaders, and OURS research mentors.
    type: info
    id: recruiting_fall_2022
    dismissable: true

open_closed_card:
  items:
    - title: Hours
      content: "Mon-Thu: 9AM-5PM<br />Fri: 8AM-4PM" 
    - title: Address
      content: 10th floor, W.E.B. Du Bois Library, 154 Hicks Way, Amherst MA
      link: https://goo.gl/maps/nXjB7p5p6CocBAKB9
    - title: Email
      content: ours@umass.edu
      link: mailto:ours@umass.edu
    - title: Make an appointment
      content: Click <a href="https://umass.campus.eab.com/">here</a> to make an appointment and <a href="assets/files/How to Make an OURS Appointment _ OURS website.pdf">here</a> to learn how to make an appointment. OURS meetings can be held in-person or over Zoom.
    # - title: Telephone
    #   content: +1 (413) 545-5334
    #   link: tel:14135455334

hours:
  ours:
    - start_day: 0
      end_day: 0
      closed: true
    - start_day: 1
      end_day: 4
      open_time: 9
      close_time: 17
    - start_day: 5
      end_day: 5
      open_time: 8
      close_time: 16
    - start_day: 6
      end_day: 6
      closed: true

homepage:
  carousel:
    items:
      - title: Opportunity Spotlight
        subtitle: <b>Mass Life Sciences Internship Challenge Summer 2022 is now open!</b><br />Paid internships for college students and recent graduates considering career opportunities in the life sciences. Students in any major are encouraged to apply, though the majority of interns have been engineering, biology, chemistry, and business majors. Placements are rolling, and there is no application deadline. However, students are urged to apply no later than April for the best chance to secure a summer placement. The internship is paid.
        image: assets/img/2015_Courtney_Babbitt_Peter_Chien_js_MG_1820.jpeg
        buttons:
          - text: Internship challenge
            link: https://www.masslifesciences.com/programs/internship-challenge/
          - text: Data science internship program
            link: https://www.masslifesciences.com/programs/datascienceinternshipchallenge/
      - title: Meet our Mentors
        subtitle:  Meet our undergraduate research mentors that can help you find research opportunities!
        image: assets/img/2014_Plant_Cell_Culture_MG_1799-2.jpeg
        buttons:
          - text: Learn more
            link: staff.html

staff:
  - name: LIN TANG, Ph.D.
    title: Director
    picture: assets/img/lin.jpg
    email: lintang@acad.umass.edu
    room: 1002
    phone: +1 (413) 545-5334

  - name: STACIE VANASSE
    title: Associate Director
    picture: assets/img/stacie2.jpg
    email: svanasse@umass.edu
    room: 1090
    phone: +1 (413) 577-2341

  - name: DEB PHILLIS
    title: OURS Coordinator and Lead Shift Manager
    picture: assets/img/deb3.jpg
    email: dphillis@acad.umass.edu
    room: 1039
    phone: +1 (413) 577-2175

  - name: ZEKE SHENK
    title: LRC Shift Manager
    email: zshenk@umass.edu

  - name: SIMON ANDREWS
    title: Tech Lead
    email: sbandrews@umass.edu

  - name: LILY ROSENBAUM
    title: Assistant Tech Lead
    email: lrosenbaum@umass.edu
