url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Learning Resource Center"

site_policies_link: https://www.umass.edu/gateway/site-policies
webmaster_email: sbandrews@umass.edu

navbar_links:
  - name: Opportunities
    link: opportunities.html
  - name: Students
    link: students.html
  - name: LRC
    link: https://www.umass.edu/lrc/

navbar_dropdown_title: Staff
navbar_dropdown_links:
  - name: Staff Page
    link: staff.html
  - name: Staff Login
    link: https://oursoffice.umass.edu/

# For every alert you would like to add, specify:
#  - text: the text for the alert, e.g. "The LRC will be closed tomorrow."
#  - type: what type the alert is/what color it should display as. Options are:
#     * info -- light blue
#     * warning -- yellow
#     * danger -- red
#  - id: should be a string of letters, numbers, and dashes ('-') that has
#        never been used as an alert ID before. I recommend generating a random
#        string from random.org.
#  - dismissable: whether users can dismiss the alert by clicking an X button
alerts:
  - text: The LRC is hiring peer tutors, SI leaders, and OURS research mentors.
    type: info
    id: recruiting_fall_2022
    dismissable: true

open_closed_card:
  items:
    - title: Hours
      content: "Mon-Thu: 9AM-5PM<br />Fri: 8AM-4PM" 
    - title: Address
      content: 10th floor, W.E.B. Du Bois Library, 154 Hicks Way, Amherst MA
      link: https://goo.gl/maps/nXjB7p5p6CocBAKB9
    - title: Email
      content: ours@umass.edu
      link: mailto:ours@umass.edu
    - title: Make an appointment
      content: Click <a href="https://umass.campus.eab.com/">here</a> to make an appointment and <a href="assets/files/How to Make an OURS Appointment _ OURS website.pdf">here</a> to learn how to make an appointment. OURS meetings can be held in-person or over Zoom.
    # - title: Telephone
    #   content: +1 (413) 545-5334
    #   link: tel:14135455334

hours:
  ours:
    - start_day: 0
      end_day: 0
      closed: true
    - start_day: 1
      end_day: 4
      open_time: 9
      close_time: 17
    - start_day: 5
      end_day: 5
      open_time: 8
      close_time: 16
    - start_day: 6
      end_day: 6
      closed: true

homepage:
  carousel:
    items:
      - title: Opportunity Spotlight
        subtitle: <b>Mass Life Sciences Internship Challenge Summer 2022 is now open!</b><br />Paid internships for college students and recent graduates considering career opportunities in the life sciences. Students in any major are encouraged to apply, though the majority of interns have been engineering, biology, chemistry, and business majors. Placements are rolling, and there is no application deadline. However, students are urged to apply no later than April for the best chance to secure a summer placement. The internship is paid.
        image: assets/img/2015_Courtney_Babbitt_Peter_Chien_js_MG_1820.jpeg
        buttons:
          - text: Internship challenge
            link: https://www.masslifesciences.com/programs/internship-challenge/
          - text: Data science internship program
            link: https://www.masslifesciences.com/programs/datascienceinternshipchallenge/
      - title: Meet our Mentors
        subtitle:  Meet our undergraduate research mentors that can help you find research opportunities!
        image: assets/img/2014_Plant_Cell_Culture_MG_1799-2.jpeg
        buttons:
          - text: Learn more
            link: staff.html

opportunities:
  - name: Five College Astronomy Undergraduate Internship
    description: The Five College Astronomy Department conducts research in a wide variety of areas, including the astrophysics of comets, stars, exoplanets, the interstellar medium, and galaxies.
    link: https://www.astro.umass.edu/academics/five-college-astronomy-undergraduate-internship-program

  - name: Five College Coastal and Marine Sciences NOAA Internship Program
    description: Interns have the opportunity to gain valuable experience conducting fieldwork, processing samples in the lab, performing data analysis, and participating in research cruises.
    link: https://www.fivecolleges.edu/five-college-coastal-marine-sciences-summer-internship-program

  - name: UConn Summer research in Biological and Biomedical Sciences
    description: UConn Health invites applications from highly qualified and motivated undergraduate students who have an interest in obtaining a Ph.D. in the biological and biomedical sciences.
    link: https://health.uconn.edu/graduate-school/academics/programs/summer/

  - name: BU School of Public Health Summer Institute for Research in Biostatistics
    description: If you are an undergraduate with an interest in mathematics, statistics, biology, or health sciences and would like to learn how to apply methods to investigate important health issues, come join us for our highly successful Summer Institute for Research Education in Biostatistics program.
    link: https://www.bu.edu/sph/about/departments/biostatistics/summer-institute-for-training-in-biostatistics

  - name: University of Missouri Dept. of Psychological Sciences Alcohol Research Training Summer School
    description: The MU-Alcohol Research Training Summer School (MU-ARTSS) is designed undergraduate students interested in alcohol research and possible careers as alcohol researchers.
    link: https://psychology.missouri.edu/research/artss/mu-artss

  - name: University of Nebraska-Lincoln Summer Research Program
    description: "The primary focus in each summer research project is biomedical devices designed to enhance medical care through science and engineering, with emphasis in two areas: (1) devices for diagnostics and sensing and (2) devices for therapeutics and intervention."
    link: https://www.unl.edu/summerprogram/biomedical

  - name: Massachusetts Life Sciences Center Internship Challenge
    description: The Massachusetts Life Sciences Center (MLSC) Internship Challenge is a workforce development program focused on enhancing the talent pipeline for Massachusetts companies engaged in life sciences.
    link: http://www.masslifesciences.com/programs/internship/

  - name: Ceres Summer Intern Program
    description: Ceres is a sustainability nonprofit organization working with the most influential investors and companies to build leadership and drive solutions throughout the economy.
    link: http://www.ceres.org/about-us/job-opportunities

  - name: Massachusetts Clean Energy Internship Program
    description: The Massachusetts Clean Energy Internship Program helps prepare the next generation of clean energy workers by funding internships for students and recent graduates at Massachusetts clean energy and water innovation companies.
    link: https://www.masscec.com/clean-energy-internship-program

  - name: Smithsonian Tropical Research Institute Panama
    description: Internships provide the opportunity to meet and work with scientists from around the world, gain hands-on experience in academia and research, and delve into Panama's rich ecosystems and culture.
    link: https://stri.si.edu/academic-programs/internships

  - name: UMass Medical School Combined Summer Undergraduate Research Opportunity
    description: UMass Medical School (UMMS) Summer Undergraduate Research Program is a structured research experience. The program consists of "hands-on" laboratory research with an investigator serving as a mentor, role model and advisor.
    link: http://www.umassmed.edu/summer/index.aspx?linkidentifier=id&itemid=152096

  - name: Blandy Research Experiences for Undergraduates (REU) Program in Ecology and Environmental Science
    description: Our primary goal is to teach students to formulate testable hypotheses about important ecological and evolutionary questions. The format of the program encourages students to develop skills in experimental design, data collection, analysis, and critical reading of primary scientific literature.
    link: https://blandy.virginia.edu/content/reu-program-ecology-and-evolution

collections:
  staff:
    output: false
